### ISSUE TITLE
Connect scheduled Meetups to Telegram groups

### ISSUE THREAD

**Issue by NicolasB58** [gillohner/dezentralschweiz_bot#26]
When organizing a new meetup, it’s important to include a question about which meetup group the event is associated with. This allows individuals who are not already members of the group to join easily.

Example:

Einundzwanzig Ostschweiz Meetups 

🎉 BITCOIN WEESEN
🕒 22.10.2024, 18:30
📍 Art-House Cocktail Bar Grütli, 37, Im Städtli, Weesen, Wahlkreis See-Gaster, St. Gallen, 8872
Group: Einundzwanzig Meetup Ostschweiz

**Comment by gillohner** [comment]
Refer to:
https://github.com/gillohner/dezentralschweiz_bot/issues/4

It should be possible to add the 31923 (single event) to multiple 31924 (calendar event).

Rough idea right now:
> User can add additional calendars at creation from a pre-defined list of calendars using inline-polling.
> /meetups gets modified in following way:
- When in regional group it checks for calendar of this group only
- In meetups channel it could either display all calendars and have a general section where events are excluded or it also goes by day.

UX is not defined yet but technical implementation is planned
